from device import (index, display,
                    delete, delete_post, add_template_select,
                    add_template_set, add_template_post,
                    disable, disable_post, enable, enable_post,
                    recreate_template_select, recreate_template_set,
                    recreate_template_post, copy, copy_post, export,
                    rack_unit_occupied, rack_unit_occupied_post,
                    rack_unit_reserved, rack_unit_reserved_post,
                    rack_unit_unoccupied,
                    rack_unit_unreserved,
                    )
